name: CI/CD MLflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CSV_URL: train_pca.csv
  TARGET_VAR: Target

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout Kode dari Repo
    - uses: actions/checkout@v3

    # 2. Siapkan Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Install Dependensi (MLflow)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow

    # 4. Training Model (Jalanin MLflow Project)
    - name: Run MLflow Project
      run: mlflow run . --env-manager=local

    # 5. Ambil Run ID Eksperimen Terakhir (Otomatis)
    - name: Get Latest Run ID
      run: |
        echo "RUN_ID=$(ls -t mlruns/0 | head -n 1)" >> $GITHUB_ENV

    # 6. Build Docker Image (Paketkan Model jadi Image 'cc')
    - name: Build Docker Image
      run: |
        mlflow models build-docker -m "runs:/${{ env.RUN_ID }}/model" -n "cc"

    # 7. Login ke Docker Hub (Pakai Secrets)
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # 8. Kasih Label (Tag) ke Image
    - name: Tag Docker Image
      run: docker tag cc ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest

    # 9. Upload (Push) ke Docker Hub
    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest