name: CI/CD MLflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CSV_URL: train_pca.csv
  TARGET_VAR: Target

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout Kode (Update ke v4)
    - uses: actions/checkout@v4

    # 2. Siapkan Python (Update ke v5)
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    # 3. Install Dependensi
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow scikit-learn pandas joblib matplotlib

    # 4. Training Model
    - name: Run MLflow Project
      run: mlflow run . --env-manager=local

    # 5. Ambil Run ID
    - name: Get Latest Run ID
      run: |
        echo "RUN_ID=$(ls -t mlruns/0 | head -n 1)" >> $GITHUB_ENV

    # 6. Build Docker Image
    - name: Build Docker Image
      run: |
        mlflow models build-docker -m "runs:/${RUN_ID}/model" -n "cc"

    # 7. Login ke Docker Hub (Update ke v3)
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # 8. Kasih Label (Tag)
    - name: Tag Docker Image
      run: docker tag cc ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest

    # 9. Upload (Push)
    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest
